#!/usr/bin/env bash

#
# Install git
#

printf "Escalated privileges are required, type in either 'doas' or 'sudo' to continue.\nNote: doas must be compiled with 'persist' capability inorder to function correctly, as its not built into the other scripts ran.\nSelection: "

while opt=$(line)
  do
    case $opt in
      "doas" )
        SUDO=${CH_SUDO:-doas}
        break
      ;;
      "sudo" )
        SUDO=${CH_SUDO:-sudo}
        break
      ;;
      *)
        echo "'$REPLY' is an invalid option!"
      ;;
  esac
done

#TODO: Laziness; using a switch case would improve script performance.
if [ -x "$(command -v emerge)" ] && [ ! -x "$(command -v git)" ]; then
  $SUDO emerge -U dev-vcs/git
elif [ -x "$(command -v pacman)" ] && [ ! -x "$(command -v git)" ]; then
  $SUDO pacman -S --needed --noconfirm git
elif [ -x "$(command -v apt)" ] && [ ! -x "$(command -v git)" ]; then
  $SUDO apt install git -y
elif [ -x "$(command -v dnf)" ] && [ ! -x "$(command -v git)" ]; then
  $SUDO dnf install -y git
fi

#
# Clone cathook
#

git clone --depth 1 https://github.com/nullworks/cathook.git

#
# Run cathook's install all script
#

pushd cathook || exit
bash ./install-all
popd || exit
